---
title: "Autocorrelation Problems"
author: Julin N Maloof
output: 
  html_document: 
    keep_md: yes
---

```{r}
library(rethinking)
library(tidyverse)
```

```{r}
files <- dir("RongkuiData/")
files
```

```{r}
datalist <- map(files, ~ read_csv(file.path("RongkuiData",.)) )
names(datalist) <- files
```

```{r}
str(datalist)
```


```{r}
LD <- datalist[[1]]
head(LD)
colnames(LD) <- tolower(colnames(LD))
table(LD$block,LD$row)

```

```{r}
LD <- LD %>%
  mutate(col=as.numeric(as.factor(col)),
         row=as.numeric(as.factor(row)))
```


```{r}
LD %>%
  filter(location=="SA") %>%
  ggplot(aes(x=col, y=row, fill=days_till_budding)) +
  geom_raster() 
```

```{r}
LD %>%
  filter(location=="DA") %>%
  ggplot(aes(x=col, y=row, fill=days_till_budding)) +
  geom_raster() 
```



```{r}
SD1 <- datalist[[2]]
head(SD1)
colnames(SD1) <- tolower(colnames(SD1))
table(SD1$block,SD1$row)
```

```{r}
SD1 <- SD1 %>%
  mutate(col=as.numeric(as.factor(col)),
         row=as.numeric(as.factor(row)))
```


```{r}
SD1 %>%
  ggplot(aes(x=col, y=row, fill=days_till_budding)) +
  geom_raster() 
```

```{r}
SD2 <- datalist[[3]]
head(SD2)
colnames(SD2) <- tolower(colnames(SD2))
table(SD2$block,SD2$row)
```

```{r}
SD2 <- SD2 %>%
  mutate(col=as.numeric(as.factor(col)),
         row=as.numeric(as.factor(row)))
```


```{r}
SD2 %>%
  ggplot(aes(x=col, y=row, fill=days_till_budding)) +
  geom_raster() 
```

## bin it:

```{r}
LDSA <- LD %>% filter(location=="SA") %>%
  as.data.frame() %>% 
  mutate(xbin=cut(col, breaks=12, labels = FALSE),
         ybin=cut(row, breaks=10, labels = FALSE),
         bin_label=str_c(str_pad(xbin,2,pad="0"),"_", str_pad(ybin, 2, pad="0"))) %>% 
  group_by(bin_label) %>%
  mutate(bin_mean=mean(days_till_budding)) %>%
  ungroup() %>%
  arrange(bin_label)
LDSA %>%
  ggplot(aes(x=xbin,y=ybin, fill=bin_mean)) +
  geom_raster()
```

```{r}
LDDA <- LD %>% filter(location=="DA") %>%
  as.data.frame() %>% 
  mutate(xbin=cut(col, breaks=12, labels = FALSE),
         ybin=cut(row, breaks=10, labels = FALSE),
         bin_label=str_c(str_pad(xbin,2,pad="0"),"_", str_pad(ybin, 2, pad="0"))) %>% 
  group_by(bin_label) %>%
  mutate(bin_mean=mean(days_till_budding)) %>%
  ungroup() %>%
  arrange(bin_label)
LDDA %>%
  ggplot(aes(x=xbin,y=ybin, fill=bin_mean)) +
  geom_raster()
```

```{r}
SD1 <- SD1 %>% 
  as.data.frame() %>% 
  mutate(xbin=cut(col, breaks=12, labels = FALSE),
         ybin=cut(row, breaks=10, labels = FALSE),
         bin_label=str_c(str_pad(xbin,2,pad="0"),"_", str_pad(ybin, 2, pad="0"))) %>% 
  group_by(bin_label) %>%
  mutate(bin_mean=mean(days_till_budding)) %>%
  ungroup() %>%
  arrange(bin_label)
SD1 %>%
  ggplot(aes(x=xbin,y=ybin, fill=bin_mean)) +
  geom_raster()
```

```{r}
SD2 <- SD2 %>% 
  as.data.frame() %>% 
  mutate(xbin=cut(col, breaks=6, labels = FALSE),
         ybin=cut(row, breaks=30, labels = FALSE),
         bin_label=str_c(str_pad(xbin,2,pad="0"),"_", str_pad(ybin, 2, pad="0"))) %>% 
  group_by(bin_label) %>%
  mutate(bin_mean=mean(days_till_budding, na.rm = TRUE)) %>%
  ungroup() %>%
  arrange(bin_label)
SD2 %>%
  ggplot(aes(x=xbin,y=ybin, fill=bin_mean)) +
  geom_raster()
```

```{r}
image(1:40, 1:40, hopkins)
```

```{r}
hopkins.l <- hopkins %>% 
  as.data.frame() %>% 
  rownames_to_column(var="ypos") %>%
  pivot_longer(-ypos, names_to = "xpos", values_to = "count", names_prefix = "V") %>%
  mutate(cell=str_c(xpos, "_", ypos)) %>%
  mutate_at(vars(ends_with("pos")), as.numeric) %>%
  mutate(xbin=cut(xpos, breaks=10, labels = FALSE),
         ybin=cut(ypos, breaks=10, labels = FALSE),
         bin_label=str_c(str_pad(xbin,2,pad="0"),"_", str_pad(ybin, 2, pad="0"))) %>% 
  group_by(bin_label) %>%
  mutate(bin_mean=mean(count)) %>%
  ungroup() %>%
  arrange(bin_label)
hopkins.l
```

```{r}
hopkins.l %>%
  ggplot(aes(x=xbin, y=ybin, fill=bin_mean)) +
  geom_raster()
  
```


```{r}
m1 <- ulam(alist(
  count ~ dnorm(mu, sig),
  mu <- a,
  a ~ dnorm(2,1),
  sig ~ dexp(1)),
  data = hopkins.l,
  chains = 4,
  log_lik = TRUE,
  cores = 4)
```

```{r}
precis(m1)
```

```{r}
Dmat <- hopkins.l %>% 
  filter(!duplicated(bin_label)) %>%
  as.data.frame() %>% 
  column_to_rownames("bin_label") %>% 
  select(xbin, ybin) %>%
  dist(diag = TRUE, upper = TRUE) %>%
  as.matrix()
dim(Dmat)
Dmat
```


```{r}
dat <- list(count=hopkins.l$count, bin_id=as.numeric(as.factor(hopkins.l$bin_label)), Dmat=Dmat )

m3nc <- ulam(alist(
  count ~ dnorm(mu, sig),
  mu <- a*exp(k[bin_id]),
  transpars> vector[100]:k <<- L_SIGMA*z,
  vector[100]:z ~ normal(0, 1),
  transpars> matrix[100, 100]: L_SIGMA <<-cholesky_decompose(SIGMA),
  transpars> matrix[100, 100]: SIGMA <- cov_GPL2( Dmat , etasq , rhosq , 0.01 ),
  a ~ dnorm(2,1),
  sig ~ dexp(1),
  etasq ~ dexp( 2 ),
  rhosq ~ dexp( 0.5 )),
  data = dat,
  chains = 4,
  log_lik = TRUE,
  cores = 4#, control = list(adapt_delta=0.99)
  )
```

```{r}
precis(m3nc, depth = 2)
```


```{r}
dat <- list(count=hopkins.l$count, bin_id=as.numeric(as.factor(hopkins.l$bin_label)), Dmat=Dmat )

m4nc <- ulam(alist(
  count ~ dnorm(mu, sig),
  mu <- a + k[bin_id],
  transpars> vector[100]:k <<- L_SIGMA*z,
  vector[100]:z ~ normal(0, 1),
  transpars> matrix[100, 100]: L_SIGMA <<-cholesky_decompose(SIGMA),
  transpars> matrix[100, 100]: SIGMA <- cov_GPL2( Dmat , etasq , rhosq , 0.01 ),
  a ~ dnorm(2,1),
  sig ~ dexp(1),
  etasq ~ dexp( 2 ),
  rhosq ~ dexp( 0.5 )),
  data = dat,
  chains = 4,
  log_lik = TRUE,
  cores = 4#, control = list(adapt_delta=0.99)
  )
```

```{r}
precis(m4nc, depth=2)
```

```{r}
compare(m1, m3nc, m4nc)
```


```{r}
Dmat2 <- hopkins.l %>% 
  as.data.frame() %>% 
  column_to_rownames("cell") %>% 
  select(xpos, ypos) %>%
  dist(diag = TRUE, upper = TRUE) %>%
  as.matrix()
dim(Dmat2)
Dmat2[1:10,1:10]
```

```{r}
dat2 <- list(count=hopkins.l$count, cell_id=as.numeric(as.factor(hopkins.l$cell)), Dmat=Dmat2 )

m5nc <- ulam(alist(
  count ~ dnorm(mu, sig),
  mu <- a*exp(k[cell_id]),
  transpars> vector[1600]:k <<- L_SIGMA*z,
  vector[1600]:z ~ normal(0, 1),
  transpars> matrix[1600, 1600]: L_SIGMA <<-cholesky_decompose(SIGMA),
  transpars> matrix[1600, 1600]: SIGMA <- cov_GPL2( Dmat , etasq , rhosq , 0.01 ),
  a ~ dnorm(2,1),
  sig ~ dexp(1),
  etasq ~ dexp( 2 ),
  rhosq ~ dexp( 0.5 )),
  data = dat2,
  chains = 4,
  log_lik = TRUE,
  cores = 4#, control = list(adapt_delta=0.99)
  )
```