---
title: "Autocorrelation Problems"
author: "Julin N Maloof"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data("hopkins", package = "spData")
head(hopkins)
library(tidyverse)
library(rethinking)
```

```{r}
image(1:40, 1:40, hopkins)
```

```{r}
hopkins.l <- hopkins %>% 
  as.data.frame() %>% 
  rownames_to_column(var="ypos") %>%
  pivot_longer(-ypos, names_to = "xpos", values_to = "count", names_prefix = "V") %>%
  mutate(cell=str_c(xpos, "_", ypos)) %>%
  mutate_at(vars(ends_with("pos")), as.numeric) %>%
  mutate(xbin=cut(xpos, breaks=10, labels = FALSE),
         ybin=cut(ypos, breaks=10, labels = FALSE),
         bin_label=str_c(str_pad(xbin,2,pad="0"),"_", str_pad(ybin, 2, pad="0"))) %>% 
  group_by(bin_label) %>%
  mutate(bin_mean=mean(count)) %>%
  ungroup() %>%
  arrange(bin_label)
hopkins.l
```

```{r}
hopkins.l %>%
  ggplot(aes(x=xbin, y=ybin, fill=bin_mean)) +
  geom_raster()
  
```


```{r}
dat <- list(count=hopkins.l$count)
m1 <- ulam(alist(
  count ~ dnorm(mu, sig),
  mu <- a,
  a ~ dnorm(2,1),
  sig ~ dexp(1)),
  data = dat,
  chains = 4,
  log_lik = TRUE,
  cores = 4)
```

```{r}
precis(m1)
```

```{r}
Dmat <- hopkins.l %>% 
  filter(!duplicated(bin_label)) %>%
  as.data.frame() %>% 
  column_to_rownames("bin_label") %>% 
  select(xbin, ybin) %>%
  dist(diag = TRUE, upper = TRUE) %>%
  as.matrix()
dim(Dmat)
Dmat
```

```{r}
Dmat0 <- hopkins.l %>% 
  as.data.frame() %>% 
  column_to_rownames("cell") %>% 
  select(xpos, ypos) %>%
  dist(diag = TRUE, upper = TRUE) %>%
  as.matrix()
dim(Dmat0)
Dmat0[1:10, 1:10]
```


```{r}

dat <- list(count=hopkins.l$count, Dmat=Dmat0, N=nrow(Dmat0), bs=sample(c(1,2),size=1600, replace = TRUE) )

mnewcent <- ulam(alist(
  count ~ multi_normal(mu, SIGMA),
  mu <- a + b*bs,
  matrix[N, N]: SIGMA <- cov_GPL2( Dmat , etasq , rhosq , 0.01 ),
  a ~ dnorm(2,1),
  b ~ dnorm(0,1),
  etasq ~ dexp( 2 ),
  rhosq ~ dexp( 0.5 )),
  data = dat,
  chains = 4,
  cores = 4#, control = list(adapt_delta=0.99)
  ,sample=TRUE)

stancode(mnewcent)
```

```{r}
dat <- list(count=hopkins.l$count, bin_id=as.numeric(as.factor(hopkins.l$bin_label)), Dmat=Dmat )

m3nc <- ulam(alist(
  count ~ dnorm(mu, sig),
  mu <- a*exp(k[bin_id]),
  transpars> vector[100]:k <<- L_SIGMA*z,
  vector[100]:z ~ normal(0, 1),
  transpars> matrix[100, 100]: L_SIGMA <<-cholesky_decompose(SIGMA),
  transpars> matrix[100, 100]: SIGMA <- cov_GPL2( Dmat , etasq , rhosq , 0.01 ),
  a ~ dnorm(2,1),
  sig ~ dexp(1),
  etasq ~ dexp( 2 ),
  rhosq ~ dexp( 0.5 )),
  data = dat,
  chains = 4,
  log_lik = TRUE,
  cores = 4#, control = list(adapt_delta=0.99)
  )
```

```{r}
precis(m3nc, depth = 2)
```


```{r}
dat <- list(count=hopkins.l$count, bin_id=as.numeric(as.factor(hopkins.l$bin_label)), Dmat=Dmat )

m4nc <- ulam(alist(
  count ~ dnorm(mu, sig),
  mu <- a + k[bin_id],
  transpars> vector[100]:k <<- L_SIGMA*z,
  vector[100]:z ~ normal(0, 1),
  transpars> matrix[100, 100]: L_SIGMA <<-cholesky_decompose(SIGMA),
  transpars> matrix[100, 100]: SIGMA <- cov_GPL2( Dmat , etasq , rhosq , 0.01 ),
  a ~ dnorm(2,1),
  sig ~ dexp(1),
  etasq ~ dexp( 2 ),
  rhosq ~ dexp( 0.5 )),
  data = dat,
  chains = 4,
  log_lik = TRUE,
  cores = 4#, control = list(adapt_delta=0.99)
  )
```

```{r}
precis(m4nc, depth=2)
```

```{r}
dat <- list(count=hopkins.l$count, bin_id=as.numeric(as.factor(hopkins.l$bin_label)), Dmat=Dmat )

m4c <- ulam(alist(
  count ~ dnorm(mu, sig),
  mu <- a + k[bin_id],
  vector[100]:k ~ multi_normal( 0 , SIGMA ),
  matrix[100,100]:SIGMA <- cov_GPL2( Dmat , etasq , rhosq , 0.01 ),
  a ~ dnorm(2,1),
  sig ~ dexp(1),
  etasq ~ dexp( 2 ),
  rhosq ~ dexp( 0.5 )),
  data = dat,
  chains = 4,
  log_lik = TRUE,
  cores = 4#, control = list(adapt_delta=0.99)
  )
```

```{r}
precis(m4c, depth=2)
```


```{r}
compare(m1, m3nc, m4nc, m4c)
```


